openapi: 3.0.3
info:
  title: Reviews API
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /reviews:
    get:
      summary: Получение списка всех рецензий
      responses:
        '200':
          description: Успешный ответ со списком рецензий
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
    post:
      summary: Добавление рецензии
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewDTO'
      responses:
        '201':
          description: Рецензия добавлена
        '400':
          description: Некорректные входные данные
  /reviews/{id}:
    parameters:
      - name: id
        in: path
        description: Уникальный идентификатор рецензии
        required: true
        schema:
          type: integer
    get:
      summary: Получение рецензии по id
      responses:
        '200':
          description: Успешный ответ рецензия найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Рецензия с указанным id не найдена
        '400':
          description: Некорректный id
    put:
      summary: Обновление данных рецензии
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewDTO'
      responses:
        '200':
          description: Данные рецензии обновлены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewDTO'
        '400':
          description: Некорректные входные данные
        '404':
          description: Рецензия с заданным id не найдена
    delete:
      summary: Удаление рецензии по id
      responses:
        '204':
          description: Рецензия удалёна
        '400':
          description: Некорректный id
        '404':
          description: Рецензия с заданным id не найдена
components:
  schemas:
    Review:
      type: object
      properties:
        id:
          type: integer
          description: Идентификатор рецензии
        publication_name:
          type: string
          description: Название публикации
        category_name:
          type: string
          description: Название рубрики
        author:
          type: string
          description: Фамилия И.О. автора
        article_name:
          type: string
          description: Название статьи
    ReviewDTO:
      type: object
      properties:
        publication_name:
          type: string
          description: Название публикации
        category_name:
          type: string
          description: Название рубрики
        article_author:
          type: string
          description: Фамилия И.О. автора статьи
        article_name:
          type: string
          description: Название статьи
        article_content:
          type: string
          description: Содержание статьи
        review_text:
          type: string
          description: Рецензия
      required:
        - publication_name
        - category_name
        - article_author
        - article_name
        - article_content
        - review_text