openapi: 3.0.3
info:
  title: Publications API
  version: 1.0.0
servers:
  - url: http://localhost:8080/

security:
  - bearerAuth: [ ]

paths:
  /publications:
    description: Доступно только главному редактору
    get:
      summary: Получение списка всех публикаций
      responses:
        '200':
          description: Успешный ответ со списком статей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicationGetDTO'
        '401':
          description: Требуется авторизация
        '403':
          description: Недостаточно прав
    post:
      summary: Создание новой публикации
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicationRequest'
      responses:
        '201':
          description: Публикация успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicationResponse'
        '400':
          description: Некорректные входные данные
        '401':
          description: Требуется авторизация
        '403':
          description: Недостаточно прав
  /publications/{id}:
    parameters:
      - name: id
        in: path
        description: Уникальный идентификатор публикации
        required: true
        schema:
          type: integer
    get:
      summary: Получение публикации по id
      responses:
        '200':
          description: Успешный ответ, публикация найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicationResponse'
        '400':
          description: Некорректный id
        '401':
          description: Требуется авторизация
        '403':
          description: Недостаточно прав
        '404':
          description: Публикация с указанным id не найдена
    put:
      summary: Обновление данных публикации
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicationRequest'
      responses:
        '200':
          description: Данные публикации обновлены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicationResponse'
        '400':
          description: Некорректные входные данные
        '401':
          description: Требуется авторизация
        '403':
          description: Недостаточно прав
        '404':
          description: Публикация с заданным id не найдена
    delete:
      summary: Удаление публикации по id
      responses:
        '204':
          description: Публикация удалена
        '400':
          description: Некорректный id
        '401':
          description: Требуется авторизация
        '403':
          description: Недостаточно прав
        '404':
          description: Публикация с заданным id не найдена
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PublicationRequest:
      type: object
      properties:
        name:
          type: string
          description: Название публикации
        publicationType:
          type: string
          enum: [ MAGAZINE, NEWSPAPER ]
        theme:
          type: string
        categories:
          type: array
          items:
            type: integer
        journalists:
          type: array
          items:
            type: integer
        editors:
          type: array
          items:
            type: integer
      required:
        - name
        - publicationType
        - theme
        - categories
        - journalists
        - editors
    PublicationGetDTO:
      type: object
      properties:
        name:
          type: string
          description: Название публикации
        publicationType:
          type: string
          description: Тип публикации
          enum: [ MAGAZINE, NEWSPAPER ]
        theme:
          type: string
          description: Тематика публикации
        categories:
          type: array
          description: Список рубрик
          items:
            $ref: '#/components/schemas/Category'

      required:
        - name
        - publicationType
        - theme
        - categories

    PublicationResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        publicationType:
          type: string
          enum: [ MAGAZINE, NEWSPAPER ]
        theme:
          type: string
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        journalists:
          type: array
          items:
            $ref: '#/components/schemas/EmployeeShort'
        editors:
          type: array
          items:
            $ref: '#/components/schemas/EmployeeShort'
      required:
        - id
        - name
        - publicationType
        - theme
        - categories
        - journalists
        - editors

    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name

    EmployeeShort:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
      required:
        - id
        - firstName
        - lastName
        - middleName