db.url=${DB_URL:jdbc:mysql://localhost:23306/cloud_publishing?useUnicode=true&characterEncoding=utf8}
db.user=${DB_USER:user}
db.password=${DB_PASSWORD:pass}
db.cachePrepStmts=true
db.prepStmtCacheSize=250
db.prepStmtCacheSqlLimit=2048
db.initializationFailTimeout=60000

jwt.secret=3563C7YujY767aDLvnWvMbIG6nzrlp7XrpCPtTp+Ip7rs
jwt.access.expiration.ms=3600000
jwt.refresh.expiration.ms=604800000